platform :ios, '7.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

def pods
	pod 'MJExtension'
	pod 'AFNetworking'
	pod 'ShareSDK3'
	pod 'MOBFoundation'
	pod 'ShareSDK3/ShareSDKUI' 
	pod 'ShareSDK3/ShareSDKPlatforms/QQ'
	pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
	pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
	pod 'FDFullscreenPopGesture_Bell'
	pod 'DKNightVersion'
	pod 'MJRefresh'
	pod 'SDWebImage'
    pod 'BaiduMapKit' #百度地图SDK
    pod 'GDataXML-HTML'
    pod 'PPNetworkHelper'
end
target 'henews250' do
	pods
end
